### ISSUE TITLE
Object has no attribute 'MetadataList'

### ISSUE THREAD

**Issue by danbr890** [paretech/klvdata#13]
When running `/examples/pprint_medata_values.py` I get the following error. It seems independent of the .bin klv file that is passed into it as I have tried with several.

`python pprint_metadata_values.py 
Traceback (most recent call last):
  File "pprint_metadata_values.py", line 10, in <module>
    metadata=packet.MetadataList()
AttributeError: 'UASLocalMetadataSet' object has no attribute 'MetadataList'
`
I'm new to klvmetadata, trying to figure out whats going on here.

**Comment by paretech** [comment]
Dan,

Can you submit a sample of the offending binary file? If you are, please
make sure it does not contain any sensitive information.

-Matt

**Comment by All4Gis** [comment]
Hi Dan

baybe your video have other standar,if not have the current klvdata parsers,if you can and it's not confidential information, to be able to reproduce it it's better to have an example

**Comment by danbr890** [comment]
I was using the sample .mpg video from ffmepg.

I'm new to this klv format and learning the ropes here.

**Comment by paretech** [comment]
Dan, do you have a link to the video?

**Comment by danbr890** [comment]
I was using the ffmpeg example video linked on the readme, http://samples.ffmpeg.org/MPEG2/mpegts-klv/Day%20Flight.mpg

**Comment by All4Gis** [comment]
what operating system are you using? I can not reproduce this error on windows using the same video.

Can you explain all steps,for better help you

**Comment by florentincostache** [comment]
I have exactly the same issue in Slackware Linux, Python 3.6.6.

**Comment by All4Gis** [comment]
@florentincostache how installed the library? the master version of github should not have that problem

**Comment by phoenixinwater** [comment]
Hey guys, the issue is probably because the package installed using pip is out of date.
MetaDataList is not included in setparser.py and a huge chunk of misb0601.py is commented out.

**Comment by All4Gis** [comment]
Thanks @phoenixinwater for your comment,you're right the pip package is not regenerated! @paretech Can you generate the package with the master version?

**Comment by All4Gis** [comment]
Update pip package and have includes MetadataList function!
