### ISSUE TITLE
Update pip

### ISSUE THREAD

**Issue by All4Gis** [paretech/klvdata#18]
Update pip package with new changes and test it

**Comment by paretech** [comment]
I started a review of PR-15 and submitted some comments for discussion.

**Comment by paretech** [comment]
New [contributing guide (CONTRIBUTING.md) ](https://github.com/paretech/klvdata/blob/master/CONTRIBUTING.md) posted as part of resolution of issue #21. Please review the contributing guidelines and propose changes per new process. Please feel free to reach out to me directly via email if you have any questions or difficulty in the process and I'll work with you to resolve. 

I'm closing this issue as a new release is not ready at this time. When the enhancement proposals (i.e. new issues) are opened we can evaluate release schedule. 

As an aside, the master branch is always deploy ready so users anxious to use the latest changes prior to a new formal release can pip install from VCS using the following command.

```
pip install git+https://github.com/paretech/klvdata.git
```
