### ISSUE TITLE
EG0104 support (Predator UAV Basic Universal Metadata Set)

### ISSUE THREAD

**Issue by ltbam** [paretech/klvdata#24]
Does this Library already support the Predator UAV Basic Universal Metadata Set (EG0104)?
 Is it already planned to support it or no work has been done yet?

**Comment by paretech** [comment]
The KLVDATA library does presently support EG0104 but it was designed to be easily extensible by user code or by enhancements to the library. 

For example, if you examine https://github.com/paretech/klvdata/blob/master/klvdata/misb0601.py, you will see how to use the @StreamParser.add_parser decorator can be used to add a new Universal Set parser to the primary stream parser.

-Matt

**Comment by ltbam** [comment]
Thank you for your answer paratech!

Then if there is nothing done I'll implement this and make a PR.

I found the file you mention and have been able to decode some values from EG0104 KLV. But I'm still struggling to decode and map lon/lat value that I receive from the KLV. I got for example:

Longitude: b'@\x1f\xc1#\xdf\xff\xfe9'       ->     1F C1 23 DF FF FE 39
Latitude : b'@Gq\xe9\xe0\x00\x00\x02'   ->     47 71 E9 E0 00 00 02

and I've not been able to decode to a proper float Lon/lat value.

If you have any idea where to search please share :-)

regards

**Comment by All4Gis** [comment]
@itbam  If you make a fork, maybe I can help you in your task.
can you publish it and some sample data?

**Comment by ltbam** [comment]
Thx @All4Gis I've contacted the software reseller and I meet today a specialist. EG0104 encoded KLV uses IEEE 754. From there, we should be able to tackle this point. I'll make a fork and put some example in it.

**Comment by ltbam** [comment]
Ok Implemented in PR:
https://github.com/paretech/klvdata/pull/25
