### ISSUE TITLE
Outputting parsed dict

### ISSUE THREAD

**Issue by JDeanThomas** [paretech/klvdata#30]
Not so much an bug as a documentation wall.

I'm having trouble getting the stream parser to output in any other way than via pprint.

CSVs from individual video files is the goal, but dicts as raw strings would be workable.

Does packet.MetadataList() not return a standard dict?

for packet in klvdata.StreamParser(sys.stdin.buffer.read()): #packet.structure()
			metadata=packet.MetadataList()
			pprint.pprint(metadata) 

is the only thing that will yield an output.

**Comment by paretech** [comment]
@JDeanThomas, thank you for your interest in klvdata and for sharing the feedback. 

The interface to parsed data is something that could be improved upon in both documentation and implementation.

If you are looking for dictionary access to parsed elements of each packet checkout the ‘items’ attribute of 'klvdata.misb0601.UASLocalMetadataSet' as it contains an ordered dict with keys as byte formatted tags and value as UASLocalMetadataSet parser objects. For example, packet.items[b’\x02’] would return 'klvdata.misb0601.PrecisionTimeStamp'. 

Packet.Structure() will print an indentured representation of the packet and any nested structures in order received. It is not intended to be a production call, more for debug.

Packet.MetadataList() returns an ordered dictionary with keys that are integer representation of tags and value as list of (item.LDSName, item.ESDName, item.UDSName, str(item.value.value)). See setparser.py for implementation. I can not longer recall the usecase, probably residual debug for some specific case…

The API could use some serious cleaning up...
