### ISSUE TITLE
Add Example for Setting KLV Data

### ISSUE THREAD

**Issue by willdueease** [paretech/klvdata#34]
As a new user, I cannot figure out how to pack metadata into a data stream. 

The provided examples are great for visualizing how to extract tags from the provided .bin file, but how would I go about doing the opposite? 

Essentially, how would I generate an example PacketData.bin to feed into the existing examples?

**Comment by All4Gis** [comment]
That's a good question. There's not much documentation on that, I made a first approximation to it here https://github.com/All4Gis/QGISFMV/blob/master/code/manager/QgsMultiplexor.py#L26  I've been looking for years and trying to do that, always without success, if you succeed don't forget to share the solution

**Comment by All4Gis** [comment]
I have created an example with python and gstreamer, I think it is a good place to start, although it is not finished.
https://gist.github.com/All4Gis/509fbe06ce53a0885744d16595811e6f
