### ISSUE TITLE
Process frames, process the frames and extracting meta data

### ISSUE THREAD

**Issue by ramdhan1989** [paretech/klvdata#35]
I have .ts file recorded by drone. I would like to run my python script for object detection for each frame in the .ts video file. Currently, I am using opencv capture to read the frames. cv2.cv.CV_CAP_PROP_FRAME_COUNT returns 37082302. meanwhile, it only around 5000 frames in the end of looping. There must be other data in .ts file since the difference is huge (37082302 vs 5000 frames). I need to detect object as well as get the meta data associated with each frame. I wonder if this package could help my problem ?

thank you

**Comment by All4Gis** [comment]
This project is just to extract the metadata. If you want to do more things you should implement the functions.

I have a project to treat the video and extract the information from each frame,draw on video, object tracking etc . You could implement your new features there.

https://github.com/All4Gis/QGISFMV
