### ISSUE TITLE
Gstreamer Example?

### ISSUE THREAD

**Issue by seabass1217** [paretech/klvdata#44]
Hi,

First off, thank you for this package.

I'm wondering if there's  a Gstreamer example similar to the FFmpeg Quick Start example?

Thanks,

**Comment by All4Gis** [comment]
No sorry, we don't have any examples here. Maybe you can find something in google

**Comment by seabass1217** [comment]
Thanks!

**Comment by pktiuk** [comment]
@seabass1217    Have you found anything?
